# -*- coding: utf-8 -*-
"""analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_AXx8qEVCSytccPyCivWhOnmWl3SC9cz
"""

import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("attendance.csv", names=["Name", "Date", "Time"])

counts = df["Name"].value_counts()

plt.figure(figsize=(6,4))
counts.plot(kind="bar")
plt.title("Attendance Count")
plt.xlabel("Name")
plt.ylabel("Days Present")
plt.tight_layout()
plt.savefig("attendance_analysis.png")
plt.show()
