# -*- coding: utf-8 -*-
"""encode_faces.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_AXx8qEVCSytccPyCivWhOnmWl3SC9cz
"""

import face_recognition
import os
import pickle

dataset_path = "known_faces"

encodings = []
names = []

for person in os.listdir(dataset_path):
    person_path = os.path.join(dataset_path, person)

    for img in os.listdir(person_path):
        img_path = os.path.join(person_path, img)

        image = face_recognition.load_image_file(img_path)
        face_enc = face_recognition.face_encodings(image)

        if face_enc:
            encodings.append(face_enc[0])
            names.append(person)

data = {"encodings": encodings, "names": names}

with open("face_encodings.pkl", "wb") as f:
    pickle.dump(data, f)

print("Encodings saved")